name: Run Wassim docker X python

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test_python:
    name: Run Python Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install coverage flake8 pdoc
          pip install -r requirements.txt

      - name: Run unit tests with coverage
        run: |
          coverage run -m unittest discover tests
          coverage report -m
          coverage xml  # Génère un rapport XML pour publication

      - name: Run Flake8 for code quality
        run: flake8 main.py tests/test_main.py

      - name: Generate documentation
        run: pdoc --html --output-dir docs main.py

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.xml

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/

  test_docker:
    name: Run Tests Inside Docker
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        run: |
          docker --version

      - name: Build Docker image
        run: |
          docker build -t fizzbuzz-app .

      - name: Run tests inside Docker
        run: |
          docker run --rm fizzbuzz-app python -m unittest discover tests
